### ISSUE TITLE
Missing packages from environment

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-sage#3]
Using the environment file provided in the package, these 3 packages are missing that are necessary to execute bespoke-fit:

* rich
* openff-utilities
* openff-fragmenter

```
$ openff-bespoke prepare -i ../../schemas/optimizations/vdw-v1-td-opt-v1.json
```

Error traces:

rich
```
Traceback (most recent call last):
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/bin/openff-bespoke", line 5, in <module>
    from openff.bespokefit.cli import cli
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/cli/__init__.py", line 1, in <module>
    from openff.bespokefit.cli.cli import cli
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/cli/cli.py", line 3, in <module>
    from openff.bespokefit.cli.executor import executor_cli
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/cli/executor/__init__.py", line 1, in <module>
    from openff.bespokefit.cli.executor.executor import executor_cli
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/cli/executor/executor.py", line 3, in <module>
    from openff.bespokefit.cli.executor.launch import launch_cli
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/cli/executor/launch.py", line 5, in <module>
    import rich
ModuleNotFoundError: No module named 'rich'
```

openff-utilities

```
>>> openff-bespoke prepare -i ../../schemas/optimizations/vdw-v1-td-opt-v1.json
Traceback (most recent call last):
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/bin/openff-bespoke", line 5, in <module>
    from openff.bespokefit.cli import cli
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/cli/__init__.py", line 1, in <module>
    from openff.bespokefit.cli.cli import cli
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/cli/cli.py", line 3, in <module>
    from openff.bespokefit.cli.executor import executor_cli
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/cli/executor/__init__.py", line 1, in <module>
    from openff.bespokefit.cli.executor.executor import executor_cli
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/cli/executor/executor.py", line 5, in <module>
    from openff.bespokefit.cli.executor.run import run_cli
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/cli/executor/run.py", line 9, in <module>
    from openff.bespokefit.cli.executor.submit import _submit, submit_options
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/cli/executor/submit.py", line 7, in <module>
    from openff.utilities import get_data_file_path
ModuleNotFoundError: No module named 'openff.utilities'
```

openff-fragmenter

```
>>> openff-bespoke prepare -i ../../schemas/optimizations/vdw-v1-td-opt-v1.json

Traceback (most recent call last):
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/bin/openff-bespoke", line 5, in <module>
    from openff.bespokefit.cli import cli
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/cli/__init__.py", line 1, in <module>
    from openff.bespokefit.cli.cli import cli
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/cli/cli.py", line 4, in <module>
    from openff.bespokefit.cli.prepare import prepare_cli
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/cli/prepare.py", line 7, in <module>
    from openff.bespokefit.optimizers import get_optimizer
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/optimizers/__init__.py", line 1, in <module>
    from openff.bespokefit.optimizers.base import (
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/optimizers/base.py", line 7, in <module>
    from openff.bespokefit.optimizers.forcebalance import ForceBalanceOptimizer
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/optimizers/forcebalance/__init__.py", line 1, in <module>
    from openff.bespokefit.optimizers.forcebalance.factories import ForceBalanceInputFactory
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/optimizers/forcebalance/factories.py", line 36, in <module>
    from openff.bespokefit.schema.fitting import OptimizationStageSchema
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openff/bespokefit/schema/fitting.py", line 4, in <module>
    from openff.fragmenter.fragment import WBOFragmenter
ModuleNotFoundError: No module named 'openff.fragmenter'
```

**Comment by SimonBoothroyd** [comment]
Thanks for raising this @lilyminium - this is unfortunately because you are installing a newer version of `bespokefit` by pip and now has these extra dependencies.

If you want to see the exact versions of the dependencies used as well as the inputs used in the full sage refits these should be available in the release tarball!

Once a C-F version of bespokefit is available in the next couple of weeks I'll be sure to update this repo with the correct install.
