### ISSUE TITLE
Cannot run `nonbonded` setup scripts

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-sage#5]
I do not have the credentials for the Heroku app. I'm admittedly confused why it is necessary to upload data to the app (edit: i.e. if it is record-keeping only or functional in some way).

```
(openff-sage) [lilyw7@hpc3-20-19:/pub/lilyw7/pydev/openff-sage/scripts]$ python setup-vdw-v1.py
ERROR:root:{"detail":"Not authenticated"}
Traceback (most recent call last):
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/nonbonded/library/models/models.py", line 71, in _upload
    request.raise_for_status()
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://nonbonded.herokuapp.com/api/dev/projects/openff-force-fields/studies/sage/optimizations/
Traceback (most recent call last):
  File "/dfs6/pub/lilyw7/pydev/openff-sage/scripts/setup-vdw-v1.py", line 129, in <module>
    main()
  File "/dfs6/pub/lilyw7/pydev/openff-sage/scripts/setup-vdw-v1.py", line 125, in main
    optimization.upload()
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/nonbonded/library/models/models.py", line 99, in upload
    return self._upload(requests_class.post, self._post_endpoint())
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/nonbonded/library/models/models.py", line 71, in _upload
    request.raise_for_status()
  File "/data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://nonbonded.herokuapp.com/api/dev/projects/openff-force-fields/studies/sage/optimizations/
```

**Comment by SimonBoothroyd** [comment]
Apologies for this @lilyminium - the line that tries to 'upload' the schema should like be replaced with something like:

```
with temporary_cd(os.path.join(os.pardir, "inputs-and-results", "optimizations")):

        OptimizationInputFactory.generate(
            optimization,
            "openff-force-fields",
            max_time="168:00",
            evaluator_preset="lilac-dask",
            evaluator_port=8000,
            n_evaluator_workers=60,
            include_results=False,
        )
```

I'll go ahead and update the script once the new version of `nonbonded` is released in the next few days.
